var eb = vertx.eventBus();

eb.consumer('com.test.app2:1001', function(pMessage) {
    var instance = pMessage.body();
    var data = instance.data;
    var inputData = instance.inputData;
    if (inputData) {


    instance.inputData = null;
    }

    eb.send('io.flowly.engine:flow.instance.hop', pMessage.body());
});

eb.consumer('com.test.app2:1003', function(pMessage) {
    var instance = pMessage.body();
    var data = instance.data;

    /* ############### Begin inline script: 1429372764270 ############### */
data.emailTo = [];

for (var i=0; i<2; i++) {
    var to = "client" + i + "@flow.ly";

    data.emailTo.push(to);
}

data.emailSubject = "Decision outcome";
data.emailBody = "This message has been auto-generated by flowly. <br/> Thanks! <br/><br/>-- Aragorn";

data.index = 0;
    /* ############### End inline script ############### */

    eb.send('io.flowly.engine:flow.instance.hop', pMessage.body());
});

eb.consumer('com.test.app2:1005', function(pMessage) {
    var instance = pMessage.body();
    var data = instance.data;
    var connectingObjectIds = [];

    if (data.index < data.emailTo.length) {
        connectingObjectIds.push('1006');
    }
    else {
        connectingObjectIds.push('1008');
    }

    instance.metaData.currentStep._flowObjectConnectingObjectIds_ = connectingObjectIds;

    eb.send('io.flowly.engine:flow.instance.hop', pMessage.body());
});

eb.consumer('com.test.app2:1007', function(pMessage) {
    var instance = pMessage.body();
    var data = instance.data;

    /* ############### Begin inline script: 1429372764271 ############### */
data.index++;
    /* ############### End inline script ############### */

    eb.send('io.flowly.engine:flow.instance.hop', pMessage.body());
});

eb.consumer('com.test.app2:1009', function(pMessage) {
    var instance = pMessage.body();
    var data = instance.data;
    var outputData = {};

    eb.send('io.flowly.engine:flow.instance.hop', pMessage.body());
});

