var eb = vertx.eventBus();

eb.consumer('com.test.app2:4001', function(pMessage) {
    var instance = pMessage.body();
    var data = instance.data;
    var inputData = instance.inputData;
    if (inputData) {


    instance.inputData = null;
    }

    eb.send('io.flowly.engine:flow.instance.hop', pMessage.body());
});

eb.consumer('com.test.app2:4003', function(pMessage) {
    var instance = pMessage.body();
    var data = instance.data;

    /* ############### Begin inline script: 1429372764300 ############### */
data.emailTo = [];

for (var i=0; i<2; i++) {
    var to = "test" + i + "@flowly.io";

    data.emailTo.push(to);
}

data.emailSubject = "Sub flow test";
data.emailBody = "This message has been auto-generated by flowly unit test.";
    /* ############### End inline script ############### */

    eb.send('io.flowly.engine:flow.instance.hop', pMessage.body());
});

eb.consumer('com.test.app2:4005', function(pMessage) {
    var instance = pMessage.body();
    var data = instance.data;
    var inputData = {};
    inputData.emailTo = data.emailTo;
    inputData.emailSubject = data.emailSubject;
    inputData.emailBody = data.emailBody;

    instance.inputData = inputData;

    eb.send('io.flowly.engine:flow.instance.hopInto', pMessage.body());
});

eb.consumer('com.test.app2:4005-io.flowly.engine:flow.instance.hopOut', function(pMessage) {
    var instance = pMessage.body();
    var data = instance.data;
    var outputData = instance.outputData;
data.success = outputData.success;

    instance.outputData = null;
    eb.send('io.flowly.engine:flow.instance.hop', pMessage.body());
});

eb.consumer('com.test.app2:4007', function(pMessage) {
    var instance = pMessage.body();
    var data = instance.data;
    var outputData = {};

    eb.send('io.flowly.engine:flow.instance.hop', pMessage.body());
});

